apiVersion: v1
kind: Pod
metadata:
  name: w-command-pod
spec:
  hostNetwork: true
  securityContext:
    runAsUser: 0
  containers:
  - name: w-command-container
    image: nginx
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: host-files
      mountPath: /host
    securityContext:
      privileged: true
  volumes:
  - name: host-files
    hostPath:
      path: /

